- job:
    name: ansible-role-diskimage-builder-base
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    roles:
      - zuul: openstack/ansible-role-diskimage-builder

# Testing for diskimage_builder_install_method: pip
- job:
    name: ansible-role-diskimage-builder
    parent: ansible-role-diskimage-builder-base
    vars:
      diskimage_builder_install_method: pip

- job:
    name: ansible-role-diskimage-builder-fedora-latest
    parent: ansible-role-diskimage-builder
    nodeset: fedora-latest

- job:
    name: ansible-role-diskimage-builder-ubuntu-bionic
    parent: ansible-role-diskimage-builder
    nodeset: ubuntu-bionic

# Testing for diskimage_builder_install_method: git
- job:
    name: ansible-role-diskimage-builder-src
    parent: ansible-role-diskimage-builder-base
    required-projects:
      - name: openstack/diskimage-builder
    vars:
      diskimage_builder_git_update: false
      diskimage_builder_install_method: git

- job:
    name: ansible-role-diskimage-builder-src-fedora-latest
    parent: ansible-role-diskimage-builder-src
    nodeset: fedora-latest

- job:
    name: ansible-role-diskimage-builder-src-ubuntu-bionic
    parent: ansible-role-diskimage-builder-src
    nodeset: ubuntu-bionic

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
    check:
      jobs:
        - ansible-role-diskimage-builder-fedora-latest
        - ansible-role-diskimage-builder-ubuntu-bionic
        - ansible-role-diskimage-builder-src-fedora-latest
        - ansible-role-diskimage-builder-src-ubuntu-bionic
        - tox-linters
    gate:
      jobs:
        - ansible-role-diskimage-builder-fedora-latest
        - ansible-role-diskimage-builder-ubuntu-bionic
        - ansible-role-diskimage-builder-src-fedora-latest
        - ansible-role-diskimage-builder-src-ubuntu-bionic
        - tox-linters
