---
- name: Define diskimage_builder_build_depends.
  set_fact:
    diskimage_builder_build_depends: "{{ __diskimage_builder_build_depends | list }}"
  when: diskimage_builder_build_depends is not defined

- name: Define diskimage_builder_depends.
  set_fact:
    diskimage_builder_depends: "{{ __diskimage_builder_depends | list }}"
  when: diskimage_builder_depends is not defined

- include: install/debian.yaml
  when: ansible_os_family == 'Debian'

- include: install/redhat.yaml
  when: ansible_os_family == 'RedHat'

- include: install/git.yaml
  when: diskimage_builder_install_method == 'git'

- include: install/pip.yaml
  when: diskimage_builder_install_method == 'pip'
